apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: andrusdiaz
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - bombona.yaml
  - slime.yaml
images:
  - name: andrusdiaz-home
    newName: southamerica-east1-docker.pkg.dev/gen-lang-client-0331944990/kaido-group/andrusdiaz
    newTag: 20260913-home-6
  - name: bombona
    newName: southamerica-east1-docker.pkg.dev/gen-lang-client-0331944990/kaido-group/bombona
    newTag: 20260913-games-1
  - name: slime
    newName: southamerica-east1-docker.pkg.dev/gen-lang-client-0331944990/kaido-group/slime
    newTag: 20260913-games-1
